--!strict
-- Copyright (c) 2026 Dr. A. Emre ÇETİN. All Rights Reserved.
-- Protected under U.S. Patent Application No. 64/148,668.
-- IdemNPC: Zero-GC In-Place AI Suite for Roblox

local IdemNPC = require(script.IdemNPC)
local IdemSwarm = require(script.IdemSwarm)
local IdemSpatialGrid = require(script.IdemSpatialGrid)

return {
	IdemNPC = IdemNPC,
	IdemSwarm = IdemSwarm,
	IdemSpatialGrid = IdemSpatialGrid,
	version = "0.1.0",
}

